### ISSUE TITLE
Argument Parser: error: unrecognized arguments: --trainscript train_transcriptions.json

### ISSUE THREAD

**Issue by tphankr** [quocdat32461997/emorecom#27]
Hello author and everyone,
I faced the error: "Argument Parser: error: unrecognized arguments: --trainscript train_transcriptions.json"
![image](https://user-images.githubusercontent.com/37217354/111062141-89a4f600-847d-11eb-9702-0b1968c993d8.png)
(python preprocess.py --test-size 0.2 --training --image warm-up-train/train --trainscript warm-up-train/train_transcriptions.json --label warm-up-train/train_emotion_labels.csv --output train.tfrecords --val-output val.tfrecords
)

I also setup files, as following: 
+ public_data has the warm-up-train folder and warm-up-test folder, ....
      + in warm-up-train has **the train folder** and **train_emotion_labels.csv** and **train_transcrptions.json**

![image](https://user-images.githubusercontent.com/37217354/111062293-63cc2100-847e-11eb-923f-2d596f4c70c7.png)
![image](https://user-images.githubusercontent.com/37217354/111062314-7e05ff00-847e-11eb-94d3-9f6385f885b6.png)

![image](https://user-images.githubusercontent.com/37217354/111062277-4303cb80-847e-11eb-893c-fbd7b0d4c3bd.png)

![image](https://user-images.githubusercontent.com/37217354/111062327-8b22ee00-847e-11eb-9ac0-25d8fe8106e5.png)

Thank you, the author.

**Comment by quocdat32461997** [comment]
@tphankr thanks for visiting the repo.

```
python preprocess.py --test-size 0.2 --training --image warm-up-train/train --trainscript warm-up-train/train_transcriptions.json --label warm-up-train/train_emotion_labels.csv --output train.tfrecords --val-output val.tfrecords
```
In your command, you got the typo **--trainscript**. Change from **--trainscript** to **--transcript**.

Also, there is a global variable **DEFAULT_PATH** that points to the dir **dataset**. It assumes all data under the **dataset**  dir. 

Hope it helps.

**Comment by tphankr** [comment]
> @tphankr thanks for visiting the repo.
> 
> ```
> python preprocess.py --test-size 0.2 --training --image warm-up-train/train --trainscript warm-up-train/train_transcriptions.json --label warm-up-train/train_emotion_labels.csv --output train.tfrecords --val-output val.tfrecords
> ```
> 
> In your command, you got the typo **--trainscript**. Change from **--trainscript** to **--transcript**.
> 
> Also, there is a global variable **DEFAULT_PATH** that points to the dir **dataset**. It assumes all data under the **dataset** dir.
> 
> Hope it helps.

Thank you very much @quocdat32461997,
I solved. Thank you very much. My results, as following:
![image](https://user-images.githubusercontent.com/37217354/111094298-662b8b00-8511-11eb-8ae2-023ae0b0dac3.png)

**Comment by quocdat32461997** [comment]
Yup now you should have tfrecord files for training. Still, you should look at branch “model_1” that I updated more frequently.

I close the issue now. Please reopen if you need help.
