### ISSUE TITLE
Error when run the commend:  bash predict.py

### ISSUE THREAD

**Issue by tphankr** [quocdat32461997/emorecom#28]
**Describe the bug**
When I ran: bash predict.py. Have some errors, as following: 
![image](https://user-images.githubusercontent.com/37217354/111144969-250d9800-855e-11eb-9eab-695c0a0841c3.png)
predict.py: line 3: $'\npredict.py - prediction module\n': command not found
from: can't read /var/mail/tensorflow.keras
from: can't read /var/mail/emorecom.data
predict.py: line 19: syntax error near unexpected token `('
predict.py: line 19: `DIR_PATH = os.getcwd(

**The code**
![image](https://user-images.githubusercontent.com/37217354/111143434-2c33a680-855c-11eb-811c-04e25b8acebb.png)

**Steps to reproduce the behavior:**
1. With the errors and my solve: 
![image](https://user-images.githubusercontent.com/37217354/111145232-69993380-855e-11eb-8e28-ed3f78d14f44.png)
2. With errors:
![image](https://user-images.githubusercontent.com/37217354/111145796-0bb91b80-855f-11eb-8cce-fc8ffe7a14cb.png)
I google and fllow this website (http://installfights.blogspot.com/2016/12/from-cant-read-varmail-in-python-scripts.html)  and add more ' !/usr/bin/env python' at the line 4 or 5 in the predict.py file. 
![image](https://user-images.githubusercontent.com/37217354/111148027-897e2680-8561-11eb-9588-c869a6e1c7f8.png)

With 2 errors as above, not solved. Please help me, thank you to the authors @quocdat32461997, and everyone. **Now I faced errors:**
![image](https://user-images.githubusercontent.com/37217354/111147366-c7c71600-8560-11eb-9477-674e36e44281.png)

**My environment (please complete the following information): (please complete the following information):**
python 3.5.6 
TensorFlow 2.2.0

**Comment by quocdat32461997** [comment]
it was a typo in the README.md that was fixed in the branch **model_1**. The master branch will not be updated until the end of the competition.
you should either type **bash predict.sh**  (default arguments) or **python3 predict.py** with custom arguments (you should look at predict.py for details of arguments).

**Comment by tphankr** [comment]
> it was a typo in the README.md that was fixed in the branch **model_1**. The master branch will not be updated until the end of the competition.
> you should either type **bash predict.sh** (default arguments) or **python3 predict.py** with custom arguments (you should look at predict.py for details of arguments).

Thank you very much author @quocdat32461997. I am going to following your GitHub in order to learn this problem ( I don't also know yet, how to set up arguments but I will try. Because I am a newbie and want to learn more things from your Github,  Please update it when you can and the end of the competition. Thank you very much @quocdat32461997 and everyone.

**Comment by quocdat32461997** [comment]
Thanks for the words. I closed the issue. Please reopen if needed.
